title: Singapore Food Manufacturers
url: https://fhafnb-sgpav.com.sg
favicon: /images/New SFMA Logo.jpg
colors:
  primary-color: "#e7131a"
  secondary-color: "#fb433d"
  media-colors:
    - title: media-color-one
      color: "#d91218"
    - title: media-color-two
      color: "#f57262"
    - title: media-color-three
      color: "#fcd6ca"
    - title: media-color-four
      color: "#414042"
    - title: media-color-five
      color: "#7f7f7f"
description: Find out more about Singapore Food Manufacturers' quality offerings!
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://enterprisesg-fha-staging.netlify.app
prod: https://enterprisesg-fha-prod.netlify.app
shareicon: ""
is_government: false
facebook-pixel: ""
google_analytics: G-DS26X98J9G
linkedin-insights: ""
